server:
  port: 8002
spring:
  redis:
    host: 192.168.2.9
    port: 6379
    password:
    timeout: 1000
    database: 1
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0
#下面是 Redis 集群配置
#    sentinel:
#      master: master1
#      nodes: 172.16.33.216:16001,172.16.33.216:16002
  main:
    allow-bean-definition-overriding: true